name: "Repocket"
slug: "repocket"
description: "Turn your unused internet into cash"
init: false
legacy: true
arch:
  - aarch64
  - amd64
version: "1.1.43"
image: repocket/repocket
options:
  RP_EMAIL: ""
  RP_API_KEY: ""
schema:
  RP_EMAIL: str
  RP_API_KEY: str
